<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CloudKeeperSN.Application\CloudKeeperSN.Application.csproj" />
    <ProjectReference Include="..\CloudKeeperSN.Domain\CloudKeeperSN.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Google.Apis.Drive.v3" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CloudKeeperSN.Application.Tests" />
  </ItemGroup>
</Project>
