<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CloudKeeperSN.Application\CloudKeeperSN.Application.csproj" />
    <ProjectReference Include="..\CloudKeeperSN.Domain\CloudKeeperSN.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
</Project>
